theme: jekyll-theme-minimal
title: Denis Narush
logo: https://avatars0.githubusercontent.com/u/2277140
description: Senior Front-End Engineer from Belarus. Have more than 12 years of commercial and 7 years of mentoring experience. HTML, CSS, JS (TypeScript), Angular, Ionic
