theme: jekyll-theme-minimal
title: Denis Narush
logo: https://avatars0.githubusercontent.com/u/2277140
description: Experienced with Angular, Ionic, TypeScript, RxJS, Nx, Javascript, html, css. Have strong debugging/analytical skills. Researching of animations and visual effects what can blow the mind from CSS3 to WebGL2. Focusing on business needs, performance optimizations.
